import { Meal, Order, Cook } from '../types';

export const MOCK_COOKS: Cook[] = [
  {
    id: 'c1',
    name: 'Sunita Aunty',
    initials: 'SA',
    avatarColor: '#E8825A',
    rating: 4.9,
    totalOrders: 84,
    cuisine: 'Punjabi',
    story: 'Made this with my mother\'s recipe from Ludhiana. Always use full cream!',
  },
  {
    id: 'c2',
    name: 'Lakshmi Amma',
    initials: 'LA',
    avatarColor: '#C45C26',
    rating: 4.8,
    totalOrders: 112,
    cuisine: 'Andhra',
    story: 'My grandmother\'s Guntur spice blend. The secret is roasting the masala fresh.',
  },
  {
    id: 'c3',
    name: 'Heena Ben',
    initials: 'HB',
    avatarColor: '#7B5EA7',
    rating: 5.0,
    totalOrders: 63,
    cuisine: 'Gujarati',
    story: 'Jain recipe, completely no-onion no-garlic. Pure and simple.',
  },
  {
    id: 'c4',
    name: 'Mary Chechi',
    initials: 'MC',
    avatarColor: '#1B6CA8',
    rating: 4.7,
    totalOrders: 45,
    cuisine: 'Kerala',
    story: 'Netholi fish from the market this morning. Coconut oil, raw mango — the real way.',
  },
  {
    id: 'c5',
    name: 'Priya Didi',
    initials: 'PD',
    avatarColor: '#388E3C',
    rating: 4.6,
    totalOrders: 77,
    cuisine: 'North Indian',
    story: 'Soaked the rajma overnight. No shortcuts — that\'s how maa taught me.',
  },
];

export const MOCK_MEALS: Meal[] = [
  {
    id: 'm1',
    name: 'Dal Makhani + 3 Rotis',
    description:
      'Slow-cooked black lentils in a rich tomato-cream gravy, served with freshly made phulkas. A family favourite that Sunita Aunty has been making for 20 years.',
    price: 120,
    emoji: '🫕',
    cuisine: 'Punjabi',
    tags: ['Veg', 'Homestyle'],
    cook: MOCK_COOKS[0],
    distanceKm: 0.8,
    etaMinutes: 25,
    rating: 4.9,
    reviewCount: 84,
    items: ['Dal Makhani (1 serving)', 'Phulka Rotis (3)', 'Pickle', 'Salad'],
    batchTotal: 6,
    batchRemaining: 2,
    cookedAt: '11:30 AM',
    isAvailable: true,
  },
  {
    id: 'm2',
    name: 'Andhra Chicken Curry + Rice',
    description:
      'Fiery Andhra-style chicken curry with freshly ground Guntur chilli masala, served with steamed sona masuri rice. Authentically spicy.',
    price: 160,
    emoji: '🍛',
    cuisine: 'Andhra',
    tags: ['Non-Veg', 'Spicy'],
    cook: MOCK_COOKS[1],
    distanceKm: 1.2,
    etaMinutes: 30,
    rating: 4.8,
    reviewCount: 112,
    items: ['Chicken Curry (1 serving)', 'Steamed Rice', 'Rasam', 'Papad'],
    batchTotal: 4,
    batchRemaining: 4,
    cookedAt: '12:00 PM',
    isAvailable: true,
  },
  {
    id: 'm3',
    name: 'Methi Thepla + Pickle',
    description:
      'Soft, fresh methi theplas made with fenugreek leaves and whole wheat flour. Jain-friendly — no onion, no garlic.',
    price: 80,
    emoji: '🫓',
    cuisine: 'Gujarati',
    tags: ['Veg', 'Jain'],
    cook: MOCK_COOKS[2],
    distanceKm: 0.5,
    etaMinutes: 15,
    rating: 5.0,
    reviewCount: 63,
    items: ['Methi Thepla (4 pcs)', 'Mango Pickle', 'Yogurt'],
    batchTotal: 10,
    batchRemaining: 8,
    cookedAt: '10:45 AM',
    isAvailable: true,
  },
  {
    id: 'm4',
    name: 'Kerala Fish Curry + Rice',
    description:
      'Traditional Kerala fish curry with raw mango, coconut milk, and fresh curry leaves. Cooked in pure coconut oil.',
    price: 190,
    emoji: '🐟',
    cuisine: 'Kerala',
    tags: ['Non-Veg', 'Coastal'],
    cook: MOCK_COOKS[3],
    distanceKm: 2.1,
    etaMinutes: 35,
    rating: 4.7,
    reviewCount: 45,
    items: ['Fish Curry (1 serving)', 'Red Rice', 'Pappadom', 'Pickle'],
    batchTotal: 5,
    batchRemaining: 3,
    cookedAt: '12:30 PM',
    isAvailable: true,
  },
  {
    id: 'm5',
    name: 'Rajma Chawal + Raita',
    description:
      'Slow-cooked kidney beans in a tangy tomato-onion gravy. Served with fluffy basmati rice and cooling cucumber raita.',
    price: 110,
    emoji: '🍲',
    cuisine: 'North Indian',
    tags: ['Veg', 'Comfort'],
    cook: MOCK_COOKS[4],
    distanceKm: 1.5,
    etaMinutes: 20,
    rating: 4.6,
    reviewCount: 77,
    items: ['Rajma (1 serving)', 'Basmati Rice', 'Cucumber Raita', 'Papad'],
    batchTotal: 8,
    batchRemaining: 5,
    cookedAt: '11:00 AM',
    isAvailable: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'MAS2847',
    meal: MOCK_MEALS[0],
    quantity: 1,
    status: 'delivered',
    total: 155,
    placedAt: 'Today, 12:34 PM',
    deliveryAddress: 'Banjara Hills, Hyderabad',
    estimatedDelivery: '1:05 PM',
  },
  {
    id: 'MAS2801',
    meal: MOCK_MEALS[1],
    quantity: 1,
    status: 'preparing',
    total: 195,
    placedAt: 'Today, 12:30 PM',
    deliveryAddress: 'Banjara Hills, Hyderabad',
    estimatedDelivery: '1:15 PM',
  },
  {
    id: 'MAS2745',
    meal: MOCK_MEALS[2],
    quantity: 2,
    status: 'delivered',
    total: 175,
    placedAt: 'Yesterday, 7:30 PM',
    deliveryAddress: 'Banjara Hills, Hyderabad',
    estimatedDelivery: '8:00 PM',
  },
];

export const CUISINE_FILTERS = [
  'All',
  'Veg',
  'Non-Veg',
  'Punjabi',
  'Andhra',
  'Gujarati',
  'Jain',
  'Kerala',
  'North Indian',
];

export const ORDER_STATUS_CONFIG = {
  placed: {
    label: 'Order Placed',
    emoji: '📋',
    color: '#78909C',
  },
  accepted: {
    label: 'Cook Accepted',
    emoji: '👩‍🍳',
    color: '#1565C0',
  },
  preparing: {
    label: 'Preparing',
    emoji: '🍳',
    color: '#E65100',
  },
  out_for_delivery: {
    label: 'Out for Delivery',
    emoji: '🛵',
    color: '#6A1B9A',
  },
  delivered: {
    label: 'Delivered!',
    emoji: '✅',
    color: '#2E7D32',
  },
  cancelled: {
    label: 'Cancelled',
    emoji: '❌',
    color: '#C62828',
  },
};
